apiVersion: apps/v1
kind: Deployment
metadata:
  name: br-app2-deployment
  namespace: br-app2
spec:
  selector:
    matchLabels:
      app: br-app2
  template:
    metadata:
      labels:
        app: br-app2
    spec:
      containers:
        - name: br-app2-php
          image: ziaulhaque/br-app2:a1c83c24-1678012089 # {"$imagepolicy": "flux-system:br-app2-repository-policy"}
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: database-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "512m"
          volumeMounts:
            - name: br-app2
              mountPath: /app
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - >
                    chmod -R 777 /app

            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "sleep 30"
        - name: br-app2-nginx
          image: nginx:1.22
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "512m"
          volumeMounts:
            - name: br-app2
              mountPath: /app
            - name: br-app2-nginx-default-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - "sleep 30"
      volumes:
        - name: br-app2
          emptyDir: {}
        - name: br-app2-nginx-default-conf
          configMap:
            name: br-app2-nginx-default-conf
