kind: ConfigMap
apiVersion: v1
metadata:
  name: br-app2-nginx-default-conf
  namespace: br-app2
data:
  default.conf: |
   server {
       listen 80;   
       index index.php index.html;
       server_name _;
   
       root /public_html/public;
       client_max_body_size 12M;
   
       location / {
           index index.php index.html index.htm;
           try_files $uri $uri/ /index.php$is_args$args;
       }
   
       location ~ \.php$ {
           try_files $uri =404;
           fastcgi_split_path_info ^(.+\.php)(/.+)$;
           fastcgi_pass 127.0.0.1:9000;
           fastcgi_hide_header X-Service-Name;
           fastcgi_index index.php;
           include fastcgi_params;
           fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
           fastcgi_param PATH_INFO $fastcgi_path_info;
       }
   } 
