version: '3'
services:
  nginx:
    image: nginx:1.22.1-alpine
    container_name: web
    hostname: web
    restart: always
    tty: true
    ports:
      - "8081:80"
    volumes:
      - ./src:/app
      - ./build/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app1
    networks:
      - web
  app1:
    image: multistage:v1
    container_name: app1
    hostname: app1
    restart: always
    tty: true
    working_dir: /app
    user: "1000:0"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "3"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/app
      - ./build/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./build/php/php.ini:/usr/local/etc/php/php.ini:rw
      - ./build/php/openssl.cnf:/etc/ssl/openssl.cnf:rw
    depends_on:
      - db
    networks:
      - web
  db:
    image: mysql:8.0.32
    container_name: db
    hostname: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: ziaul123456
      MYSQL_ROOT_PASSWORD: root654321
    volumes:
      - ./mysql-data:/var/lib/mysql/
    networks:
      - web

#Docker Networks
networks:
  web:
    driver: bridge
